### ISSUE TITLE
カスタムテーマの抜け漏れをなくす

### ISSUE THREAD

**Issue by htomine** [increments/mastodon#47]
## What
Dark/Lightのそれぞれのテーマについて、デフォルトのスタイルからの変更漏れがある箇所がある。
該当箇所を洗い出して対応する。

## Why
対応漏れのため視認性が悪くなっている箇所がほとんど。

## Todo
- [x] モバイル向けアイコンをデフォルトから Qiitadon アイコンに差し替える #39
- [x] 通報部分のスタイルがおかしい #38
- [x] Darkテーマで、CWの警告文入力フォームの文字色が見づらい #37
- [x] OGPのスタイルがテーマに対応していない #34
- [x] 通知欄でユーザー名にカーソルを合わせると消えたように見える #33
- [x] メディア画面でテーマのスタイルが当たっていない #53
- [x] 通知削除の[キャンセル]が灰色になってしまっていて見づらい #64

設定画面への対応は一旦別で考える。Mastodonロゴの配色やデザインまで変えていくか？
- [ ] https://github.com/increments/mastodon/issues/29

https://qiitadon.com/@voqn/837
上記を参考に、その他に未対応な箇所も洗い出す

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by htomine** [comment]
https://github.com/increments/mastodon/pull/40 がmergeされたあとで対応する。
